sudo: true
language: node_js
node_js: '12'
cache:
  npm: true
  yarn: true

branches:
  only:
    - gatsby

install:
  - yarn

script:
  - yarn build
  - yarn type-check

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: public
  target_branch: master
  keep_history: true
  on:
    branch: gatsby
