# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github-actions/deploy

on:
  push:
    branches: [ gatsby ]
  pull_request:
    branches: [ gatsby ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: node-14-${{ hashFiles('yarn.lock') }}
    - run: yarn
    - run: yarn build
    - run: yarn type-check
    - uses: actions/checkout@v2
      with:
        path: target
        ref: master
    - run: rm -rf target/* && mv public/* target/
    - run: git add . && git commit -m "Deploy $GITHUB_SHA" && git push master origin/master
